tests/__init__.py
So far asyncio is quite new framework and, therefore, has lack of
testing instruments. This commit introduces convenient testing
facilities such as:
* inloop decorator
.. that runs a wrapped function in newly created event loop.
* AIOTestMeta metaclass
.. that runs classes' async methods in newly created event loop.
* AIOTestApp class
.. that is a facade to test an aiohttp.web.Application instances.
=> Add testing facilities

tox.ini
Skip the step of building of an sdist and install the package in the
development mode (i.e. python setup.py develop) - this allows to
save a little time when running tests and modify files in place (e.g.
for debugging purposes) without running tox again.
=> tox: avoid building of sdist

tox.ini
skipsdist is a global var, not an env one. skip_install becomes
redundant now.
=> tox: ensure sdist step is skipped for swagger env

tests/__init__.py, tests/resources/test_snippets.py
Move the repeating initialization (e.g. app creation) and clean up
steps (e.g. DB cleanup) into setup() / teardown() method helpers,
which will be executed before and after each test case.
setup() / teardown() must be aware of the event loop instance which
was created for a particular test case, so that they can execute
appropriate actions (e.g. clean up a DB), thus, setup() / teardown()
are executed by the inloop() decorator.
=> tests: separate init and cleanup steps from test cases

.coveragerc, .travis.yml, tox.ini
So far coverage wrongly reports missed statements, and shows a bunch of
create_index calls as unevaluated. We know for sure they have been
executed, since otherwise tests will fail.
According to coverage documentation, it easily can be confused if greenlet
is used. In that case we should explicitly tell coverage that
concurrency model is greenlet.
Unfortunately, this is the case. Motor uses greenlet under the hood, and
passing concurrency=greenlet to coverage solves the issue.
=> Pass concurrency=greenlet to coverage.py

xsnippet_api/application.py, xsnippet_api/database.py
Having possibility to pass down custom event loop looks like unnecessary
complication that requires ugly workaround (see one with Motor). Let's
remove it, and may the code a little more event-loop agnostic.
=> Do not pass down event loop, use default one

xsnippet_api/database.py, xsnippet_api/default.conf
It's very convenient to setup such options like 'pool-size' through
configuration file, since one might want to turn it taking into
account server resources.
=> Add 'pool-size' to default.conf

.mailmap
The .mailmap feature is used to coalesce together commits by the same
person in the shortlog, where their name and/or email address was
spelled differently. So far '$ git shortlog -se' shows the following
output:
15  Igor Kalnitsky <igor@kalnitsky.org>
6  Roman Podoliaka <roman.podolyaka@gmail.com>
6  Roman Podoliaka <rpodolyaka@mirantis.com>
while this commit corrects it to be the following one:
16  Igor Kalnitsky <igor@kalnitsky.org>
12  Roman Podoliaka <roman.podolyaka@gmail.com>
=> Calesce together commit authors using .mailmap

tests/resources/test_snippets.py, xsnippet_api/application.py, xsnippet_api/resources/__init__.py, xsnippet_api/resources/snippets.py
Only GET requests are supported now. We'll also need to refactor
errors to be in JSON format.
=> Add a basic implementation of the Snippet resource

tests/resources/test_resource.py
Base Resource class is intended to provide basic facilities for encode
responses according to Accept HTTP header, and decore requests according
to Content-Type HTTP header. In cases these headers contain unsupported
media type the proper HTTP codes must be returned.
The commit adds a set of tests to ensure that behaviour.
=> Tests for base Resource class

tests/resources/test_snippets.py, tests/services/test_snippet.py, xsnippet_api/resources/snippets.py, xsnippet_api/services/snippet.py
It's now possible to pass additional ``limit`` and ``marker`` query
parameters to /snippets endpoint, e.g.:
GET /snippets?limit=10&marker=1234
where ``limit`` will be an upper bound for the number of snippets to
be returned and ``marker`` is the ``id`` of the last snippet seen on
the previous page. Snippets are ordered by the creation order (newer
ones will be returned first).
Marker based pagination is used instead of limit/offset one, as the
performance of the latter degrades quickly as the number of entries
grows.
=> Add marker based pagination support to /snippets

setup.py, xsnippet_api/__main__.py
* `io.open` is not used anymore in setup.py since we are py3-only project.
* Unnecessary empty lines between setup's options are removed.
* Package short description is more readable now.
* Package name is changed to 'xsnippet-api'.
=> Improve setup.py code and its metadata options

xsnippet_api/application.py, xsnippet_api/resources/snippets.py, xsnippet_api/router.py
It's generally a more convenient to do API discovering rather than
importing resources one by one and adding it to router. That makes even
more sense in light of versioning API, where the very same resource may
appear in different routers.
This commit introduces an @endpoint decorator for resources. That allows
us to declaratively map a resource to some URI and defines an API
version range where it's applicable.
No tests are introduces, since those code is explicitly covered by any
test that use create_app() factory function.
=> Discover RESTful API via @endpoint decorator

tests/test_application.py, tests/test_resource.py, xsnippet_api/application.py
The Vary HTTP response header determines how to match future request
headers to decide whether a cached response can be used rather than
requesting a fresh one from the origin server. It is used by the server
to indicate which headers it used when selecting a representation of a
resource in a content negotiation algorithm.
This commit adds three Varying headers: Accept, Accept-Encoding and
X-Api-Version.
=> Respond with 'Vary' HTTP header

.coveragerc, .travis.yml, setup.py
There are two reasons why it's necessary (yet not mandatory) to update
lower bound of Motor version. Here they are:
* Since Motor 0.7 there's another mechanism behind offloading queries to
MongoDB: previously used greenlets-based approach have been replaced with
thread pool one.
https://emptysqua.re/blog/motor-0-7/
According to the author blog post it improves performance when client
and database has a good connectivity.
* Moving away from greenlets means we can forget about out hacks around
coverage.py which affects both .coveragerc and .travis.yml.
=> Bump Motor version to at least 0.7

tests/resources/test_snippets.py, xsnippet_api/application.py, xsnippet_api/database.py
We currently mix synchronous and asynchronous code in
create_connection(), that leads to sporadic warnings in tests due to
the fact that `on_done` future callbacks are called after the event
loop instance is already closed. Apparently these futures returned
by create_index() are not awaited by the event loop as it is, so we'd
better do it explicitly, rather than hope that callbacks will be
called in time before the event loop is closed.
With this change applied I no longer run into the default limit for
the number of connections opened to mongod at the same time when
running tox -epy36.
=> db: create indexes at application startup

tests/__init__.py
Since aiohttp 2.0 the event loop isn't initialized on `web.Application`
creation; instead it's initialized later on `app.make_handler` call.
Unfortunately our tests were relied on this behaviour and tried to
retrieve an event loop instance earlier than it became available. This
commit fixes this race.
=> Make tests compatible with aiohttp 2.0

.mailmap
Due to various name spelling and/or using various emails, Git thinks
that we have plenty of contributors. For instance, here's what it
prints on `git shortlog -se` command:
40  Igor Kalnitsky <igor@kalnitsky.org>
14  Ihor Kalnytskyi <igor@kalnitsky.org>
1  Ihor Kalnytskyi <ihor@kalnytskyi.com>
6  Roman Podoliaka <roman.podoliaka@gmail.com>
20  Roman Podoliaka <roman.podolyaka@gmail.com>
Let's merge those authors using `.mailmap` and enjoy pretty, correct and
up-to-date information:
56  Ihor Kalnytskyi <ihor@kalnytskyi.com>
26  Roman Podoliaka <roman.podoliaka@gmail.com>
=> Use .mailmap to fix three Ihor(s) and two Roman(s)

tox.ini
May God and @malor forgive me, but I made several unrelated changes
to `tox.ini` in one commit. Why? I think changing three lines in
several commits including the very one that will be changed in each
of them, rather a silly idea; so there we are.
The commit accommodates the following changes:
* `py.test` executable is deprecated in favor of `pytest`, however,
it was decided to use Python module notation instead as it doesn't
rely on binary name.
* Both `pytest` and `flake8` might be available globally on the machine
(e.g. pytest on Travis CI), so let's use `{envpython}` notation
instead of binary names in order to avoid ambiguous situations.
* The `--strict` flag is passed to `pytest` to treat warnings as
errors.
* Both `pytest` and `flake8` run for the whole project instead of
just …
=> Minor enhancements in tox.ini

.travis.yml, docs/conf.py, docs/index.rst, docs/requirements.txt, tox.ini
This commit introduce a very basic Sphinx skeleton that do nothing but
renders OpenAPI spec by means of `sphinxcontrib-redoc` extension.
=> docs: produce API docs from OpenAPI spec

contrib/openapi/spec.yml
Current version of OpenAPI spec contains non-implemented parts of API as
well as missed some valuable information regarding authentication or
pagination. This commit removes unimplemented parts from the spec and
brings more details on other parts.
=> Document API in OpenAPI specification

tests/__init__.py
Apparently, `Server.finish_connections` had been deprecated since
aiohttp version 1.2 and was eventually removed. As we depend on
1.2+, we can safely use the replacement - `Server.shutdown`.
=> Fix the failing tests due to new release of aiohttp

.gitignore, tox.ini
Build a new image using the short commit id as a tag:
$ tox -e docker-build
Note, that if the working directory contains uncommitted changes,
a special `wip` tag will be used instead of the commit id.
Build a new image with a given tag:
$ tox -e docker-build -- latest
=> Add a tox env for building a Docker image

contrib/openapi/spec.yml, tests/resources/test_snippets.py, tests/services/test_snippet.py, xsnippet_api/database.py, xsnippet_api/resources/snippets.py, xsnippet_api/services/snippet.py
It's now possible to pass additional query parameters `title` and
`tag`, so that only the snippets that have corresponding attribute
values are returned, e.g.:
GET /snippets?title=foo&tag=bar
Filtering by title is implemented by searching for all the matches,
that start with the given string (both for efficiency and
feature-parity reasons).
=> Add support for filtering by title and tag

contrib/ansible/deploy.yaml, contrib/ansible/docker-compose.yml.j2, contrib/ansible/xsnippet-api.conf.j2
The playbook allows to deploy xsnippet-api on a clean Ubuntu Xenial
machine, e.g.:
$ ansible-playbook -u user \
-e xsnippet_image=xsnippet/xsnippet-api:latest \
contrib/ansible/deploy.yaml
`xsnippet_image` variable can be used to specify the exact Docker
image, that should be deployed (it is expected, that the image has
already been built and pushed to the registry).
The playbook also deploys xsnippet-api dependencies like MongoDB.
=> Add a basic ansible playbook for deployment

tox.ini
There's no need to run tox for few Python 3.x versions by default
because most of the time machines don't have them installed at the
same time. For CI purposes, we explicitly pass Python versions
we want to run anyway.
Also, let's check docs by default. :)
=> Use py3, openapi and docs as default Tox envs

tests/resources/test_snippets.py, tests/services/test_snippet.py, xsnippet/api/database.py, xsnippet/api/resources/snippets.py, xsnippet/api/services/snippet.py
We plan to use "author" and "is_public" attributes for snippets but we
are not there yet. Let's remove them from the model and API for the sake
of simplicity. Since they are top-level we can simply add them anytime
preserving backward compatibility.
=> Remove unused snippet attributes

contrib/ansible/xsnippet-api.conf.j2, tests/resources/conftest.py, tests/resources/test_snippets.py, tests/resources/test_syntaxes.py, xsnippet/api/resources/__init__.py, xsnippet/api/resources/syntaxes.py
This new endpoint allows to retrieve the list of supported snippet
syntaxes, that is defined in the config file. Modify the default
config to contain the list of syntaxes from the original XSnippet.
Put the test fixtures into conftest.py, so that they can be reused
in tests of different API resources.
=> Add GET /syntaxes endpoint

tests/resources/conftest.py, tests/resources/test_snippets.py, tests/services/test_snippet.py, xsnippet/api/resources/snippets.py, xsnippet/api/services/snippet.py
PUT & PATCH HTTP methods are intended to change snippet attributes by
authenticated owners. This is a first step towards changesets.
The difference between PUT and PATCH is in the following:
* PUT replaces snippet entity in the database. Any missed attributes will
be reset to default.
* PATCH updates entity in the database. Any missed attributes will be
kept untouched.
=> Implement PUT & PATCH for /snippets/{id} endpoint

xsnippet/api/application.py, xsnippet/api/resources/snippets.py, xsnippet/api/resources/syntaxes.py
We want to have our code base as much clean as we can get, and that
involved removing custom code that doesn't bring much profit. One of
such example is custom `@endpoint` decorator that was designed to do
resources auto collection. This commit removes one, and starts using
plain `UrlDispatcher()` instances to build route map.
=> Remove custom `@endpoint` decorator

xsnippet/api/application.py, xsnippet/api/resources/snippets.py, xsnippet/api/resources/syntaxes.py
We use to set VersionRouter instance on application later in the code by
exploiting private attribute. The need of this hack comes from the time
when UrlDispatcher (router) was needed to be aware of the application,
and the application was needed to be aware of router on creation time.
In aiohttp v2.3.5 (we depend on) it's no more the case. So let's remove
the hack and use intended design.
=> Remove router assignment via app._router property

tests/resources/test_snippets.py, xsnippet/api/database.py, xsnippet/api/services/snippet.py
The idea of marker-based pagination is that users pass the id of
the last item on a page that was returned in order to obtain the
next page.
On the db side we use the given id to find the "specimen" document
first and then use the "key" value (in our case we sort by value of
`created_at` attribute) to efficiently find the position of the
specimen document in a db index and then select the following `$limit`
documents (note, that we use btree indexes, which store all the keys
in some order, so the db just needs to follow btree node pointers -
no sorting is actually performed).
In order to avoid the ambiguity of multiple documents with the same
value of `created_at` attribute, we used a compoud sorting key -
`(_id, created_at)`. The problem with that was that we did not have
a compound …
=> Improve the efficiency of pagination

tests/resources/test_snippets.py, xsnippet/api/resources/snippets.py, xsnippet/api/services/snippet.py
In order to have feature parity with running xsnippet service we need
to provide a way to filter snippets by syntax, i.e. show only snippets
with a certain syntax.
=> Add snippets filtering by syntax

xsnippet/api/__main__.py
Our logs are utterly quite, let's make sure we also write access/error
logs to stderr and not only the tracebacks for unhandled exceptions.
=> Write access/error logs to stderr

tests/resources/test_snippets.py, tox.ini, xsnippet/api/resource.py, xsnippet/api/resources/snippets.py, xsnippet/api/services/snippet.py
When traversing the list of snippets page by page provide an additional
response header - Link - that contains the links to the previous and
the next page with the given value of limit (if such pages exist).
This follows the idea from:
https://developer.github.com/v3/guides/traversing-with-pagination/
and
https://tools.ietf.org/html/rfc5988
Hopefully, this will make using of pagination easier on the client
side.
=> Provide Link response header for pagination

xsnippet/api/__main__.py, xsnippet/api/default.conf
Make sure we've got the most important information like remote addr,
request status line, response code, response size, user agent and
request processing time, e.g:
```
[10/Jan/2018:21:00:14 +0000] 127.0.0.1 "GET /snippets?limit=5 HTTP/1.1" 200 233 curl/7.54.0" 0.030207
```
Note, that for production deploys behind a reverse-proxy this format
might be changed to use the HTTP headers like X-Real-IP or
X-Forwarded-For, if needed.
Partially closes #59
=> Tweak the default acccess log format

tests/test_resource.py, xsnippet/api/resource.py, xsnippet/api/resources/snippets.py, xsnippet/api/resources/syntaxes.py
RESTfulness is weird word, I know, but the idea is to provide a base
class for purposes of building RESTful APIs. Gosh, it sounds complex
so here's what was changed:
* Resource classes now return tuples instead of 'web.Response()' of
the following format: (data, status_code, headers). Where both
status_code and headers are optional and can be omitted. From now
one, content negotiation is done by resource class implicitly.
* Exception translation to proper HTTP response is done by Resource
class either. So far domain exceptions are hardcoded now, but they
will become optional very soon once I figure out the better API for
parametrization. :)
=> Make Resource class more "RESTful"

tests/middlewares/test_auth.py, xsnippet/api/application.py, xsnippet/api/middlewares/auth.py
Since aiohttp 2.3, old-style middlewares are deprecated [1] and hence
may be removed any time soon. Taking into account this fact, it'd be
better if rewrite our internal "auth" middleware to be a new-style
middleware as it may live longer than the former.
[1] https://docs.aiohttp.org/en/stable/web.html#old-style-middleware
=> Rewrite "auth" middleware as new-style middleware

tests/test_router.py, xsnippet/api/application.py, xsnippet/api/router.py
We used to fallback to latest stable API version when 'Api-Version'
header was omitted. While it made sense when we were using version
discovery mechanism, it makes a little sense now when all versions
are statically defined.
Since now it's more garbage and complication, not saying it doesn't
give us control on which version to serve by default, let's remove
this function now.
=> Use explicitly set API version when not passed

contrib/docker/Dockerfile
Since we install the app in the container by running `pip install` the
app will be copied over to some `/usr/lib/python3/site-packages` place.
That basically means we don't the sources in the container afterwards,
so why just not remove them to avoid ambiguousness about which code
is actually used to run the app?
=> Remove /app directory (sources) from Docker image

tests/conftest.py, tests/test_resource.py, xsnippet/api/resource.py
Since most modern APIs support only JSON and XSnippet is not an exception
here, it makes sense to assume JSON if 'Content-Type' and/or 'Accept'
headers aren't passed.
=> Assume 'Content-Type: application/json' by default

setup.py, xsnippet/api/application.py, xsnippet/api/resource.py, xsnippet/api/resources/snippets.py
Every now and again, aiohttp continue to break XSnippet API. As we
try to keep up with bleeding edge technologies it's time to update the
code base and become compatible with latest aiohttp.
Most noticeable changes from our code base point of view are:
* request.GET multi-dict is renamed to request.query
* app.on_response_prepare signal now receives only coroutines
* web.View() must implement __await__() instead of __iter__() now
It seems aiohttp tries to follow semantic version, so along with bumping
minimal supported version let's prevent potential failures by setting
upper constraint as well.
=> Bump aiohttp up to 3.0

tests/resources/test_snippets.py, xsnippet/api/services/snippet.py
We used to have sort of weird behaviour by defaulting snippet's 'syntax'
to 'text' if it wasn't specified at the first place. While it'd make
sense on certain situations, it's something we want to avoid in
XSnippet, because we might want to know whether it's something submitted
by user or not.
Clearly there are two options to go with:
(a) Require 'syntax' to be explicitly passed in POST and PUT requests.
(b) Assume 'syntax' is 'None' if not passed.
In case of option (a) we have an open question: what to do if we didn't
set a list of allowed syntaxes? Should we force users to pass any syntax
even if it doesn't matter?
In case of option (b) an open question is opposite: what to do if we set
a list of allowed syntaxes? Should we ignore this implicit 'syntax'
value and allow to store 'None'? …
=> Do not default 'syntax' to 'text' if not passed

tests/test_application.py, xsnippet/api/__main__.py, xsnippet/api/application.py, xsnippet/api/middlewares/auth.py
There are couple of reasons of doing so but the main one is to make
middleware to be responsible for validating tokens only, moving
responsibility of getting secret (reading from config or generating one)
from middleware (as it's supposed to be as general as possible) to
consumers.
It'd make even more sense once we implement /auth endpoint that would be
responsible for issuing JWT tokens, meaning that the middleware is not
the only owner of authentication.
=> Generate secret in main rather than in middleware

tests/test_resource.py, xsnippet/api/resource.py
Apparently we didn't have tests for malformed input payload and used to
fall with 500 Internal Server Error if input payload is not
de-serializable. o_O Luckily we found it early and from now on we will
return 400 Bad Request in this case.
=> Return 400 Bad Request on malformed input JSON

setup.py, tests/conftest.py
Picobox 2.0 provides first citizens functions to `push()` and `pop()` boxes
to and from stack; no more weird `__enter__()` / `__exit__()` explicit calls
to context manager.
=> Update Picobox to 2.0

xsnippet/api/application.py, xsnippet/api/routes.py
Usually routes are shared between application instances, so there's no
real need to define them in-place in some application factory functions.
And if we move them into separate routes.py, we can make the project
easier for being explored by providing a single entry point (API) from
which everyone can traverse deep down to what they're looking for.
=> Move API routes into separate routes.py

tests/conftest.py, tests/middlewares/test_auth.py, tests/test_resource.py, tests/test_router.py
Since aiohttp 3.0 test_client fixture has been renamed into
aiohttp_client. While the old name still works for a while we better
keep up with the latest changes because it won't last forever and will
be removed in future versions.
=> Use aiohttp_client fixture instead of test_client

tests/resources/test_snippets.py, xsnippet/api/resources/snippets.py
Snippet with no content (i.e. content is "") is nonsense and noise, so
we better reject such snippets to be protected from noise and bots.
=> Do not allow empty snippets

tests/test_application.py, xsnippet/api/application.py
It turns out that most browsers ignore this header and implement their
own caching based on other headers (like Last-Modified, etc). So let's
remove this from a code base and configure Vary (if needed) later on
reverse proxy side.
=> Remove Vary header from response

Dockerfile
`python:latest` size is ~900 Mb, which sounds a lot for such a simple
app as xsnippet-api; we don't really need all that stuff. Use
`python:slim` image as a base instead, that is much smaller (~130 Mb).
As we still need some external tools like git to be pre-installed
in order to produce an xsnippet-api wheel, we use the new Docker
multi-stage builds feature: the first stage is responsible for
collecting all the necessary Python wheels (including xsnippet-api
itself); the second stage only copies the artifacts and installs
them to a slim image.
See Docker docs for details:
https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
=> docker: use python:slim as a base to reduce the image size

Dockerfile, tests/test_conf.py, xsnippet/api/__main__.py, xsnippet/api/conf.py
We only have a handful of settings and should be fine with using of
environment variables instead.
=> Drop support for reading of configuration from an INI-file

.pre-commit-config.yaml, .travis.yml, tox.ini
pre-commit is built to solve the hook issues. It is a multi-language
package manager for pre-commit hooks. You specify a list of hooks you
want and pre-commit manages the installation and execution of any hook
written in any language before every commit. pre-commit is specifically
designed to not require root access. If one of your developers doesn’t
have node installed but modifies a JavaScript file, pre-commit
automatically handles downloading and building node to run eslint
without root.
It's a common trend, at least among Python projects, to use this
software to run various lint checks.
https://pre-commit.com/
=> Add pre-commit-config.yaml

.pre-commit-config.yaml, docs/conf.py, setup.py, tests/conftest.py, tests/middlewares/test_auth.py, tests/resources/test_snippets.py, tests/resources/test_syntaxes.py, tests/test_application.py, tests/test_conf.py, tests/test_resource.py, tox.ini, xsnippet/api/__init__.py, xsnippet/api/__main__.py, xsnippet/api/application.py, xsnippet/api/conf.py, xsnippet/api/database.py, xsnippet/api/middlewares/__init__.py, xsnippet/api/middlewares/auth.py, xsnippet/api/resource.py, xsnippet/api/resources/__init__.py, xsnippet/api/resources/misc.py, xsnippet/api/resources/snippets.py, xsnippet/api/resources/syntaxes.py, xsnippet/api/routes.py, xsnippet/api/services/__init__.py, xsnippet/api/services/snippet.py
By using Black, we agree to cede control over minutiae of
hand-formatting. In return, Black gives us speed, determinism, and
freedom from pycodestyle nagging about formatting.
Black makes code review faster by producing the smallest diffs possible.
Blackened code looks the same regardless of the project we’re reading.
Formatting becomes transparent after a while and we can focus on the
content instead.
=> Use Black to format the code

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, diesel.toml, src/main.rs, src/storage/mod.rs, src/storage/sql/migrations/2020-07-25-065258_create_snippets/down.sql, src/storage/sql/migrations/2020-07-25-065258_create_snippets/up.sql, src/storage/sql/mod.rs, src/storage/sql/schema.rs
Diesel is used for schema migrations (written in raw SQL; targetting
PostgreSQL at the moment) and conversions between SQL and Rust
data types.
=> Initial database schema

src/application.rs, src/main.rs, src/routes/syntaxes.rs
Dealing with snippets, XSnippet API has a notion of syntaxes, one may consider using to highlight the snippet on the web or perform some actions in other clients. These syntaxes may differ based on supported syntaxes in XSnippet Web, or needs of others when this service is ran on premises.
This patch adds parametrization via Rocket's built-in facilities, such as `Rocket.toml` or `ROCKET_SYNTAXES` environment variable. The variable must be a list of strings.
```
$ ROCKET_SYNTAXES=["rust", "python"] cargo run
```
By default, no syntaxes are used.
=> Parametrize a set of supported syntaxes on start

.github/workflows/tests.yml, Cargo.lock, Cargo.toml, src/application.rs, src/storage/errors.rs, src/storage/mod.rs, src/storage/models.rs, src/storage/sql/migrations/env.py, src/storage/sql/mod.rs, src/storage/sql/models.rs
Trait `Storage` defines a basic CRUD interface for storing/loading snippets from a persistent database. The only implementation planned as of now is `SqlStorage,` which only supports PostgreSQL at the moment, while in the future it should be relatively easy to extend it to support SQLite and MySQL if desired (we would need to stop using `INSERT ... ON CONFLICT DO ...` , though).
=> The initial implementation of the storage layer

src/storage/mod.rs, src/storage/models.rs, src/storage/sql/mod.rs, src/storage/sql/models.rs
In addition to the basic CRUD interface we want Storage to allow for listing snippets that satisfy the given criteria. Note, that this initial implementation does not support marker-based pagination yet.
=> Extend Storage to support listing snippets

.github/actions/setup-postgres/action.yml, .github/workflows/tests.yml
In order to improve workflows' readability, let's move the steps that
setup postgresql server into standalone action. This way it will be
easier reuse this code between the jobs, and the jobs will be much
simpler.
=> Add 'setup-postgres' action

Cargo.lock, Cargo.toml, src/storage/mod.rs, src/storage/models.rs, src/storage/sql/models.rs, src/storage/util.rs
In order to return Snippets in API responses, we need to make them serializable first. Rocket can handle serialization to JSON, but it requires the types to implement `serde::Serializable`.
In theory, we could just auto-derive that trait for our structs, but in practice it is more complicated than that, as `created_at` and `updated_at` are of type `DateTime<Utc>`, and the latter does not implement `serde::Serializable`.
Rust has this fair, but sometimes annoying requirement, that you can't implement foreign traits for foreign types. So the way to work around that is to create a wrapper struct around `DateTime<Utc>` from the chrono crate. This has no runtime/memory overhead, but it is a little verbose (because we need to handle type conversions).
=> Make Snippet and Changeset serializable

src/storage/mod.rs, src/storage/models.rs, src/storage/sql/mod.rs
Pagination based on limit+offset does not scale with the number of items (because offset is O(N)). Rework the code to use markers instead, which allows us to find the required page in O(log N).
Only basic tests are added. We will test this properly in the integration tests when we wire this code up to the API.
=> Re-implement pagination to use markers instead of limit+offset

.github/workflows/tests.yml, tests/requirements.txt, tests/test_gabbits.py
As briefly discussed in the comments to #112, we want to make the Gabbit tests more self-sufficient: given a database URL, they should be able to start an instance of xsnippet-api, including running the DB migrations by the means of alembic.
While we are at this, fix the warning emitted by SQLAlchemy: the name of the DB API driver has been changed from `postgres` to `postgresql`. Diesel is happy with both, so no change there.
=> Make Gabbit tests run DB migrations

Cargo.toml, src/application.rs, src/errors.rs, src/main.rs, src/routes/mod.rs, src/routes/snippets.rs, src/util.rs, tests/gabbits/create-snippet-errors.yaml, tests/gabbits/create-snippet.yaml
This does the bare minimum to implement the API of XSnippet v4 as closely as possible.
One caveat is that the Gabbit tests can't clean up after themselves until DELETE is implemented as well.
=> Implement the POST /snippets route

Cargo.lock, Cargo.toml, src/storage/models.rs, tests/gabbits/create-snippet.yaml
This allows us not to call .to_rfc3339() explicitly and rely on chrono choosing the correct serialization format.
One difference is that the timestamps in UTC now use the Z suffix instead of encoding the HOURS:MINUTES offset (+00:00). Both are valid representations according to the standard. Account for that in the regexp that we use in tests.
=> Use chrono with "serde" feature enabled

src/application.rs, src/routes/snippets.rs, tests/gabbits/get-snippet-errors.yaml, tests/gabbits/get-snippet.yaml
This patch imeplements a route that retrieves the snippet by ID. With
storage layer in place, it merely a few lines of Rocket shim and dozens
lines of Gabbi tests.
=> Implement the /snippets/<id> route

src/storage/models.rs, tests/gabbits/get-snippet.yaml
The latest nightly release of rustc complains that we are using `assert!()` wrong: the second argument should be a static string literal that specifies how to format the resulting error message.
=> Fix the tests on CI

.github/actions/setup-postgres/action.yml, tests/test_gabbits.py
Currently, our tests update the database state but never clean it up,which will become problematic in the future, e.g. when we implement listing of snippets.
One way to deal with this would be to delete all table rows between test runs, but that effectively wipes out the database that
ROCKET_DATABASE_URL points to, which can be destructive when used in the wrong environment, or just annoying when it drops the state of a local XSnippet API instance.
Alternatively, we can create a temporary database in start_fixture(), and use for a single Gabbi test (i.e. one YAML file with test cases).
=> Create a temporary database in the XSnippetApi fixture

Cargo.lock, Cargo.toml, src/application.rs, src/errors.rs, src/main.rs, src/storage/sql/mod.rs, src/web.rs, src/web/content.rs, src/web/tracing.rs, tests/test_gabbits.py
`tracing` is a framework that allows to set up structured logging with contextual information. In addition to traditional _events_, it also has a notion of _spans_, which are logical blocks of actions that represent a unit of work performed by an application. For web applications, it's natural to treat a single request as a span. All events logged in a context of a span will have the same structured contextual information, e.g. request id, HTTP method, URI, status code, etc.
Our current setup is very basic, but tracing can do much more:
* spans can be nested. Libraries can create their own spans, which will attach to our request spans. E.g. it may be possible to trace all SQL requests executed by Diesel for a given API request
* multiple subscribers can be configured. Instead of logging …
=> Add basic logging

Cargo.lock, src/application.rs, src/errors.rs, src/routes/snippets.rs, src/storage/mod.rs, src/storage/models.rs, src/storage/sql/mod.rs, src/web/auth.rs, src/web/auth/jwt.rs, tests/gabbits/auth.yaml, tests/gabbits/import-snippet.yaml, tests/test_gabbits.py
Normally when new snippets are created, users are not allowed to specify the values of fields which are automatically generated,   e.g. `id`, `created_at`, and `updated_at`. This would, however, be very useful for "importing" the state of the previous incarnation of XSnippet API that is currently deployed to prod (so that we can leverage the API for this instead of INSERT'ing the values directly to the database).
Importing snippets should not be allowed to anyone, but only to users with the special `import` permission.
=> Allow to "import" snippets via POST /v1/snippets/import

.github/workflows/release.yml
This will:
* create a new pre-release for every PR merged to master
* create a new release for every pushed version tag
For every release we build one binary per each supported platform (Linux, Mac OS, Windows). Note, that while Rust itself uses static linking for everything, we link against `libpq` and `libc` dynamically.
=> Add a CI workflow to build xsnippet-api executables

Cargo.toml
We are going to use the release builds in production, so we want them to have DWARF debug symbols that are also useful for CPU profiling.
=> Generate debug symbols in release builds as well

.github/workflows/release.yml
With debug symbols enabled, the built executables can get quite large, so we want to compress them to save some disk space and network bandwidth.
Also, change the asset naming convention to include the arch name.
=> Compress release assets before uploading them to Github

Cargo.lock, Cargo.toml, src/application.rs, src/errors.rs, src/routes/snippets.rs, src/storage/mod.rs, src/storage/models.rs, src/web.rs, src/web/auth/jwt.rs, src/web/content.rs, tests/gabbits/list-snippets-errors.yaml, tests/gabbits/list-snippets-filtering.yaml, tests/gabbits/list-snippets-pagination.yaml, tests/requirements.txt, tests/test_gabbits.py
We already have `POST /snippets` route that creates new snippets, but we
were missing `GET /snippets` route to list recently created snippets.
This patch implements missing route.
=> Add GET /snippets route

src/main.rs, src/storage/sql/mod.rs, tests/gabbits/imported-snippets-pagination.yaml, tests/test_gabbits.py
When listing snippets, we add filters on `created_at` and `id` to fetch the next page. The latter is only needed because the value of `created_at` is not guaranteed to be unique, so the marker can appear in the next page again. In practice, because we use microsecond precision for datetime fields, duplicates are only expected in tests and, potentially, in snippets imported from Mongo that have second precision.
As is, the code did not work correctly in the edge case when snippets were imported from the old API instance in the reverse (starting from the latest snippets) order, because the assumption, that both `created_at` and `id` monotonically increase together, did not hold true: the additional filter `id < $MARKER_ID` produced an empty result, as "older" (in terms of the value of …
=> Fix the edge case of pagination being broken for snippets imported from Mongo

.github/workflows/release.yml, src/web/auth/jwt.rs
"latest" is a bit special in a sense that Github will automatically add that label to the latest final release. Let's avoid the name clash and call it "nightly" instead.
=> Tag pre-releases as "nightly" rather than "latest"

Cargo.toml
This did not actually require any code changes, as we don't use any of
the features that have been updated, except for the new dependency
resolver in Cargo, which will now compile Rocket with some features
disabled:
> cargo fix --edition
note: Switching to Edition 2021 will enable the use of the version 2 feature resolver in Cargo.
This may cause some dependencies to be built with fewer features enabled than previously.
More information about the resolver changes may be found at https://doc.rust-lang.org/nightly/edition-guide/rust-2021/default-cargo-resolver.html
When building the following dependencies, the given features will no longer be used:
cookie v0.11.4 (as host dependency) removed features: aes-gcm, base64, hkdf, hmac, key-expansion, private, rand, secure, sha2, signed …
=> Opt-in to Rust 2021 edition

src/application.rs, src/errors.rs, src/routes/snippets.rs, src/web.rs, src/web/content.rs, tests/gabbits/get-snippet-errors.yaml, tests/gabbits/get-snippet.yaml
This route can be used to implement the "raw" URIs in the UI w/o the need to support the corresponding nginx Lua rules.
The way we have written out content negotiation system requires us to either add support for a new content type to *all* routes (which we don't want to do at this point), or to use a new request guard to make Rocket dispatch the request to a correct function (which is a bit cumbersome but still easier).
=> Add a GET /snippet/:id that allows to retrieve the raw content of a snippet as plain text

Cargo.lock, src/web/tracing.rs
Per https://github.com/xsnippet/xsnippet-api/security/dependabot, there are a few vulnerabilities in the versions we are using.
=> Update pinned dependencies

.github/workflows/release.yml, .github/workflows/tests.yml, .rustfmt.toml, Cargo.lock, Cargo.toml, src/application.rs, src/errors.rs, src/main.rs, src/routes/snippets.rs, src/routes/syntaxes.rs, src/web/auth.rs, src/web/auth/jwt.rs, src/web/content.rs, src/web/tracing.rs, tests/test_gabbits.py
We are considering ditching Rocket for axum, but, in the meantime, let's at the very least update to the latest Rocket version so that:
* we can fix all the security vulnerabilities Dependabot is complaining about
* we can use stable Rust instead of nightly
There are many backward incompatible changes, but most were due to `async` and new lifetimes sprinkled everywhere now.
One annoying bit is that we have to temporarily give up on our tracing integration: request span can no longer be created on the same thread as Tokio can move futures between threads, and the span must be created on the top-level "request" future, i.e. in Rocket itself. The code compiles, but it is disabled.
=> Update to Rocket 0.5

.github/workflows/release.yml, .github/workflows/tests.yml
* actions/checkout@v2 and actions/setup-python@v2 are using a deprecated NodeJS version
* the new setup-python action wants us to specify the Python version explicitly
* setting action output values via stdout is also deprecated (see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
=> Fix GitHub CI warnings

.github/workflows/release.yml
Those actions started triggering various deprecation warnings, and they are generally hard to use than the CLI that we can test locally.
=> Use gh instead of third-party GitHub actions for creating releases

.github/workflows/release.yml
See https://github.com/xsnippet/xsnippet-api/actions/runs/8339394829/job/22821304489. Apparentely, `repository.name` does not include the owner name (contrary to what https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables suggests...).
=> Fix the value of GH_REPO

.github/workflows/release.yml
`gh release upload` allows to set the display label, but, as it turns out, that does not change the names of the assets in the release, and the names are required to be unique. In our case, the names of the Linux and MacOS binaries clash, and the slower of them will fail to upload.
=> Fix asset uploading

Cargo.lock, Cargo.toml, src/storage/sql/models.rs, src/web/auth.rs
* Clippy now complains about struct fields that are never read. With ids it's understandable, but with errors it's just plain annoying as those are used by the implementation of the Debug trait, and yet clippy choses to ignore derived implementations
* Update the dependencies to close some security vulnerabilities
=> Fix new clippy warnings and update deps

.github/workflows/release.yml
Per https://github.blog/news-insights/product-news/introducing-artifact-attestations-now-in-public-beta/, this should allow users to verify attestations using GitHub CLI.
=> Try actions/attest-build-provenance for our builds

.github/workflows/release.yml
Per https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token, `contents: write` is required to create new releases and upload artifacts.
=> ci: fix release creation permissions

.github/workflows/release.yml, Cross.toml
GitHub does not provide a aarch64-unknown-linux-gnu runner that we would need to compile binaries for Raspberry Pi, but we can use `cross` to build those on the amd64 Ubuntu runner.
=> Cross-compile binaries for aarch64-unknown-linux-gnu (alternative)

.github/workflows/release.yml
https://github.com/xsnippet/xsnippet-api/pull/173 had a couple of issues:
* String regex test in Bash requires [[ ]] instead of [ ]
* JSON output in rustc is only available when the nightly toolchain is installed. Instead, we can form the target value manually
=> ci: quick fix for the releases workflow

.github/workflows/release.yml
1) The path is incorrect because we meant to capture the value of
`$PWD` _before_ and not after running `popd`
2) The `HOST` value is different on Mac OS (the OS part is "macos"
instead of the expected "darwin"). There appears to be no way to
get this from some structured data in stable rustc, so we resort
to grep that works on all platforms
=> ci: fix the release workflow

Cargo.lock, Cargo.toml, Cross.toml
Dynamic linking with openssl does not work well with cross-compilation: the Docker image `cross` uses for aarch64 is based on Ubuntu Xenial that has libssl1.0.0, while the ones available on Raspbian (and other modern distros) are libssl1.1 and libssl3.
Instead, we can use the feature of `openssl-sys` that allows to build and statically link openssl to avoid the hassle with shared object versions that vary between Linux distros.
This makes Cross.toml completely unnecessary.
=> Build and link with openssl statically

.github/workflows/release.yml
See https://github.com/sfackler/rust-openssl/issues/2149.
Apparently, in the Windows runner, commands executed in a `run` block will use the version of Perl built into MinGW instead of the one installed in the system, which breaks the openssl build because one of the expected Perl modules can't be found.
There are different ways to fix this. The one suggested in this PR is returning back to using the cargo action for "normal" (not cross compilation) builds like it used to work before. My understanding is that it helps by running cargo directly as opposed to running it from Bash.
Alternatively, we could bypass the corresponding build steps in openssl by providing locations of openssl source code via environment variables like it is suggested in the rust-openssl issue linked above.
=> ci: fix build error on windows

.github/workflows/release.yml, .github/workflows/tests.yml, src/storage/sql/mod.rs, src/web/tracing.rs
The new Rust compiler got a lot smarter at spotting "dead code" and started complaining about some unused bits. Turns out the snippet update feature was never fully finished — but that’s no reason to rip out parts of the storage subsystem.
On top of that, GitHub CI switched to a new macOS runner that doesn’t come with PostgreSQL pre-installed anymore. So we had to bump the action-setup-postgres version to get it running smoothly.
=> Make master green again
